apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clusterNew
  region: us-east-1
  version: "1.31"

managedNodeGroups:
  - name: workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 2

addons:
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
